/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

IF TYPE_ID('[sdCountryStringVariants].[CountryISO3]') IS NOT NULL
	DROP TYPE [sdCountryStringVariants].[CountryISO3];

GO
CREATE TYPE [sdCountryStringVariants].[CountryISO3] FROM nchar (3) NULL
GO
