/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

IF TYPE_ID('[sdVehicleDescriptorString].[VehicleIdentifier]') IS NOT NULL
	DROP TYPE [sdVehicleDescriptorString].[VehicleIdentifier];

GO
CREATE TYPE [sdVehicleDescriptorString].[VehicleIdentifier] FROM nvarchar (150) NULL
GO
