/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [Analytics].[CustomerExpenditureClassification]
(
[CustomerExpenditureClassificationID] [sdSequenceNumber].[SurrogateKeyNumber] NOT NULL CONSTRAINT [XPK_CustomerExpenditureClassificationID_Sequence] DEFAULT (NEXT VALUE FOR [PKSequence].[CustomerExpenditureClassificationID]),
[CustomerExpenditureClassifier] [sdMarketingTextString].[CustomerSpendCapacity] NULL CONSTRAINT [DF_CustomerExpenditureClassification_CustomerExpenditureClassifier] DEFAULT ('Unavailable')
)
GO
ALTER TABLE [Analytics].[CustomerExpenditureClassification] ADD CONSTRAINT [PK_CustomerExpenditureClassification] PRIMARY KEY CLUSTERED ([CustomerExpenditureClassificationID])
GO
