/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [Analytics].[ManufacturerMarketingCategory]
(
[ManufacturerMarketingCategoryID] [sdSequenceNumber].[SurrogateKeyNumber] NOT NULL,
[ManufacturerVehicleMarketingType] [sdVehicleDescriptorString].[VehicleManufacturerMarketingType] NULL CONSTRAINT [DF_Template_Unavailable_458766293] DEFAULT ('Unavailable')
)
GO
ALTER TABLE [Analytics].[ManufacturerMarketingCategory] ADD CONSTRAINT [XPKManufacturerMarketingCategory] PRIMARY KEY CLUSTERED ([ManufacturerMarketingCategoryID])
GO
