/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [Analytics].[SalesCategoryThreshold]
(
[SalesCategoryThresholdID] [sdSequenceNumber].[SurrogateKeyNumber] NOT NULL,
[LowerThreshold] [sdVehicleSalePayment].[VehiclePrice] NULL CONSTRAINT [DF_SalesCategoryThreshold_LowerThreshold_Price] DEFAULT ((0.00)),
[UpperThreshold] [sdVehicleSalePayment].[VehiclePrice] NULL CONSTRAINT [DF_SalesCategoryThreshold_UpperThreshold_Price] DEFAULT ((0.00)),
[CategoryDescription] [sdMarketingTextString].[VehicleSalesThresholdCategory] NULL CONSTRAINT [DF_Template_Unavailable_1475131995] DEFAULT ('Unavailable')
)
GO
ALTER TABLE [Analytics].[SalesCategoryThreshold] ADD CONSTRAINT [CK_SalesCategoryThreshold_CategoryDescription_SalesThreshold] CHECK (([CategoryDescription]='Outstanding' OR [CategoryDescription]='Exceptional' OR [CategoryDescription]='Very High' OR [CategoryDescription]='High' OR [CategoryDescription]='Medium' OR [CategoryDescription]='Low' OR [CategoryDescription]='Very Low'))
GO
ALTER TABLE [Analytics].[SalesCategoryThreshold] ADD CONSTRAINT [CK_SalesCategoryThreshold_LowerThreshold_Price] CHECK (([LowerThreshold]>=(0.00)))
GO
ALTER TABLE [Analytics].[SalesCategoryThreshold] ADD CONSTRAINT [CK_SalesCategoryThreshold_UpperThreshold_Price] CHECK (([UpperThreshold]>=(0.00)))
GO
ALTER TABLE [Analytics].[SalesCategoryThreshold] ADD CONSTRAINT [XPKSalesCategoryThreshold] PRIMARY KEY CLUSTERED ([SalesCategoryThresholdID])
GO
