/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

IF TYPE_ID('[dEuropeanCarDealership].[dEuropeanCarManufacturer]') IS NOT NULL
	DROP TYPE [dEuropeanCarDealership].[dEuropeanCarManufacturer];

GO
CREATE TYPE [dEuropeanCarDealership].[dEuropeanCarManufacturer] FROM char (18) NULL
GO
