/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

IF TYPE_ID('[sdDate].[SaleDate]') IS NOT NULL
	DROP TYPE [sdDate].[SaleDate];

GO
CREATE TYPE [sdDate].[SaleDate] FROM date NULL
GO
