/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

IF TYPE_ID('[dNumber].[sdSequenceNumber]') IS NOT NULL
	DROP TYPE [dNumber].[sdSequenceNumber];

GO
CREATE TYPE [dNumber].[sdSequenceNumber] FROM int NOT NULL
GO
