/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [Inventory].[ManufacturerVehicleStock]
(
[ManufacturerVehicleStockID] [sdSequenceNumber].[SurrogateKeyNumber] NOT NULL IDENTITY(1, 1),
[ManufacturerVehicleModelID] [sdSequenceNumber].[SurrogateKeyNumber] NULL,
[StockCode] [sdShortTextString].[StockCode] NULL CONSTRAINT [DF_ManufacturerVehicleStock_StockCode_Unavailable] DEFAULT ('Unavailable'),
[Cost] [sdVehicleSalePayment].[VehiclePrice] NULL CONSTRAINT [DF_ManufacturerVehicleStock_Cost_Price] DEFAULT ((0.00)),
[RepairsCharge] [sdVehicleSalePayment].[CostOfFee] NULL CONSTRAINT [DF_ManufacturerVehicleStock_RepairsCharge_Price] DEFAULT ((0.00)),
[PartsCharge] [sdVehicleSalePayment].[CostOfFee] NULL CONSTRAINT [DF_ManufacturerVehicleStock_PartsCharge_Price] DEFAULT ((0.00)),
[DeliveryCharge] [sdVehicleSalePayment].[CostOfFee] NULL CONSTRAINT [DF_ManufacturerVehicleStock_DeliveryCharge_Price] DEFAULT ((0.00)),
[IsPremiumRoadHandlingPackage] [sdFlagBit].[FlagFalse] NULL CONSTRAINT [DF_ManufacturerVehicleStock_IsPremiumRoadHandlingPackage_FlagFalse] DEFAULT ((0)),
[VehicleColor] [sdVehicleDescriptorString].[VehicleColor] NULL CONSTRAINT [DF_ManufacturerVehicleStock_VehicleColor_Unavailable] DEFAULT ('Unavailable'),
[CustomerComments] [sdLongTextString].[CustomerComments] NULL CONSTRAINT [DF_ManufacturerVehicleStock_CustomerComments_Unavailable] DEFAULT ('Unavailable'),
[PurchaseDate] [sdDate].[PurchaseDate] NULL CONSTRAINT [DF_ManufacturerVehicleStock_PurchaseDate_Date] DEFAULT ('19991231'),
[Note] [sdLongTextString].[Note] NOT NULL CONSTRAINT [DF_ManufacturerVehicleStock_Note_Note] DEFAULT ('Row was inserted'),
[IsDeleted] [sdFlagString].[AuditFlag] NULL CONSTRAINT [DF_ManufacturerVehicleStock_IsDeleted_FlagNo] DEFAULT ('N'),
[TransactionNumber] [sdOrdinalNumber].[TransactionNumber] NULL CONSTRAINT [DF_ManufacturerVehicleStock_TransactionNumber_OrdinalNumber] DEFAULT ((1)),
[UserAuthorizationID] [sdSequenceNumber].[SurrogateKeyNumber] NULL,
[SysStartTime] [sdSysTime].[SysStartTime] NULL CONSTRAINT [DF_ManufacturerVehicleStock_SysStartTime_Sysdatetime] DEFAULT (sysdatetime()),
[SysEndTime] [sdSysTime].[SysEndTime] NULL CONSTRAINT [DF_ManufacturerVehicleStock_SysEndTime_SysEndTime] DEFAULT ('99991231 23:59:59.9999999')
)
GO
ALTER TABLE [Inventory].[ManufacturerVehicleStock] ADD CONSTRAINT [CK_ManufacturerVehicleStock_Cost_Price] CHECK (([Cost]>=(0.00)))
GO
ALTER TABLE [Inventory].[ManufacturerVehicleStock] ADD CONSTRAINT [CK_ManufacturerVehicleStock_DeliveryCharge_Price] CHECK (([DeliveryCharge]>=(0.00)))
GO
ALTER TABLE [Inventory].[ManufacturerVehicleStock] ADD CONSTRAINT [CK_ManufacturerVehicleStock_IsDeleted_AuditFlag] CHECK (([IsDeleted]='Y' OR [IsDeleted]='N'))
GO
ALTER TABLE [Inventory].[ManufacturerVehicleStock] ADD CONSTRAINT [CK_ManufacturerVehicleStock_IsPremiumRoadHandlingPackage_FlagBit] CHECK (([IsPremiumRoadHandlingPackage]=(1) OR [IsPremiumRoadHandlingPackage]=(0)))
GO
ALTER TABLE [Inventory].[ManufacturerVehicleStock] ADD CONSTRAINT [CK_ManufacturerVehicleStock_PartsCharge_Price] CHECK (([PartsCharge]>=(0.00)))
GO
ALTER TABLE [Inventory].[ManufacturerVehicleStock] ADD CONSTRAINT [CK_ManufacturerVehicleStock_RepairsCharge_Price] CHECK (([RepairsCharge]>=(0.00)))
GO
ALTER TABLE [Inventory].[ManufacturerVehicleStock] ADD CONSTRAINT [PK_Stock] PRIMARY KEY CLUSTERED ([ManufacturerVehicleStockID])
GO
ALTER TABLE [Inventory].[ManufacturerVehicleStock] ADD CONSTRAINT [FK_ManufacturerVehicleStock_ManufacturerVehicleModel] FOREIGN KEY ([ManufacturerVehicleModelID]) REFERENCES [Inventory].[ManufacturerVehicleModel] ([ManufacturerVehicleModelID]) ON UPDATE CASCADE
GO
