/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [Inventory].[ManufacturerVehicleMake]
(
[ManufacturerVehicleMakeID] [sdSequenceNumber].[SurrogateKeyNumber] NOT NULL IDENTITY(1, 1),
[ManufacturerVehicleMakeName] [sdVehicleDescriptorString].[VehicleIdentifier] NULL CONSTRAINT [DF_ManufacturerVehicleMake_ManufacturerVehicleMakeName_Unknown] DEFAULT ('Unavailable'),
[ManufacturerVehicleMarketingCategoryID] [sdSequenceNumber].[SurrogateKeyNumber] NULL,
[CountryID] [sdSequenceNumber].[SurrogateKeyNumber] NULL CONSTRAINT [DF_ManufacturerVehicleMake_CountryID_ForeignKeyValue] DEFAULT ((0)),
[Note] [sdLongTextString].[Note] NOT NULL CONSTRAINT [DF_ManufacturerVehicleMake_Note] DEFAULT ('Row was inserted'),
[IsDeleted] [sdFlagString].[AuditFlag] NULL CONSTRAINT [DF_Template_FlagNo] DEFAULT ('N'),
[TransactionNumber] [sdOrdinalNumber].[TransactionNumber] NULL CONSTRAINT [DF_ManufacturerVehicleMake_TransactionNumber] DEFAULT ((1)),
[UserAuthorizationID] [sdSequenceNumber].[SurrogateKeyNumber] NULL,
[SysStartTime] [sdSysTime].[SysStartTime] NULL CONSTRAINT [DF_ManufacturerVehicleMake_SysStartTime_Sysdatetime] DEFAULT (sysdatetime()),
[SysEndTime] [sdSysTime].[SysEndTime] NULL CONSTRAINT [DF_Template_SysEndTime_1062630532] DEFAULT ('99991231 23:59:59.9999999')
)
GO
ALTER TABLE [Inventory].[ManufacturerVehicleMake] ADD CONSTRAINT [CK_Template_AuditFlag_339417156] CHECK (([IsDeleted]='Y' OR [IsDeleted]='N'))
GO
ALTER TABLE [Inventory].[ManufacturerVehicleMake] ADD CONSTRAINT [PK_Make] PRIMARY KEY CLUSTERED ([ManufacturerVehicleMakeID])
GO
ALTER TABLE [Inventory].[ManufacturerVehicleMake] ADD CONSTRAINT [FK_ManufacturerVehicleMake_ManufacturerMarketingCategory] FOREIGN KEY ([ManufacturerVehicleMarketingCategoryID]) REFERENCES [Analytics].[ManufacturerMarketingCategory] ([ManufacturerMarketingCategoryID]) ON UPDATE CASCADE
GO
