/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

IF TYPE_ID('[sdPersonNameString].[FullNameString]') IS NOT NULL
	DROP TYPE [sdPersonNameString].[FullNameString];

GO
CREATE TYPE [sdPersonNameString].[FullNameString] FROM nvarchar (50) NOT NULL
GO
