/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [HumanResources].[Staff]
(
[StaffID] [sdSequenceNumber].[SurrogateKeyNumber] NOT NULL IDENTITY(1, 1),
[StaffName] [sdPersonNameString].[FullNameString] NULL CONSTRAINT [DF_Staff_StaffName_Unavailable] DEFAULT ('Unavailable'),
[DepartmentID] [sdSequenceNumber].[SurrogateKeyNumber] NULL CONSTRAINT [DF_Staff_DepartmentID_ForeignKeyValue] DEFAULT ((0)),
[ManagerID] [sdSequenceNumber].[SurrogateKeyNumber] NULL CONSTRAINT [DF_Staff_ManagerID_ForeignKeyValue] DEFAULT ((0)),
[Note] [sdLongTextString].[Note] NOT NULL CONSTRAINT [DF_Staff_Note_Note] DEFAULT ('Row was inserted'),
[IsDeleted] [sdFlagString].[AuditFlag] NULL CONSTRAINT [DF_Staff_IsDeleted_FlagNo] DEFAULT ('N'),
[TransactionNumber] [sdOrdinalNumber].[TransactionNumber] NULL CONSTRAINT [DF_Staff_TransactionNumber_OrdinalNumber] DEFAULT ((1)),
[UserAuthorizationID] [dNumber].[sdSequenceNumber] NULL CONSTRAINT [DF_Staff_UserAuthorizationID_OrdinalNumber] DEFAULT ((1)),
[SysStartTime] [sdSysTime].[SysStartTime] NULL CONSTRAINT [DF_Staff_SysStartTime_Sysdatetime] DEFAULT (sysdatetime()),
[SysEndTime] [sdSysTime].[SysEndTime] NULL CONSTRAINT [DF_Staff_SysEndTime_SysEndTime] DEFAULT ('99991231 23:59:59.9999999')
)
GO
ALTER TABLE [HumanResources].[Staff] ADD CONSTRAINT [CK_Staff_IsDeleted_AuditFlag] CHECK (([IsDeleted]='Y' OR [IsDeleted]='N'))
GO
ALTER TABLE [HumanResources].[Staff] ADD CONSTRAINT [XPKStaff] PRIMARY KEY CLUSTERED ([StaffID])
GO
