/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [Sales].[SalesOrderVehicle]
(
[SalesOrderVehicleID] [sdSequenceNumber].[SurrogateKeyNumber] NOT NULL IDENTITY(1, 1),
[CustomerID] [sdSequenceNumber].[SurrogateKeyNumber] NULL CONSTRAINT [DF_SalesOrderVehicle_CustomerID_SequenceStartingValue] DEFAULT ((0)),
[StaffID] [sdSequenceNumber].[SurrogateKeyNumber] NOT NULL CONSTRAINT [DF_SalesOrderVehicle_StaffID_ForeignKeyValue] DEFAULT ((0)),
[InvoiceNumber] [sdShortTextString].[InvoiceNumber] NULL CONSTRAINT [DF_SalesOrderVehicle_InvoiceNumber_InvoiceNumber] DEFAULT ('00000000'),
[TotalSalePrice] [sdVehicleSalePayment].[VehiclePrice] NULL CONSTRAINT [DF_SalesOrderVehicle_TotalSalePrice_Price] DEFAULT ((0.00)),
[SaleDate] [sdDate].[SaleDate] NULL CONSTRAINT [DF_SalesOrderVehicle_SaleDate_Date] DEFAULT ('19991231'),
[SalesOrderCategoryDescription] AS ([Sales].[ufnCategoryDescription_SalesOrderCategoryDescription]([TotalSalePrice])),
[Note] [sdLongTextString].[Note] NOT NULL CONSTRAINT [DF_SalesOrderVehicle_Note_Unavailable] DEFAULT ('Row was inserted'),
[IsDeleted] [sdFlagString].[AuditFlag] NULL CONSTRAINT [DF_SalesOrderVehicle_IsDeleted_FlagNo] DEFAULT ('N'),
[TransactionNumber] [sdOrdinalNumber].[TransactionNumber] NULL CONSTRAINT [DF_SalesOrderVehicle_TransactionNumber_OrdinalNumber] DEFAULT ((1)),
[UserAuthorizationID] [sdSequenceNumber].[SurrogateKeyNumber] NULL,
[SysStartTime] [sdSysTime].[SysStartTime] NULL CONSTRAINT [DF_SalesOrderVehicle_SysStartTime_Sysdatetime] DEFAULT (sysdatetime()),
[SysEndTime] [sdSysTime].[SysEndTime] NULL CONSTRAINT [DF_SalesOrderVehicle_SysEndTime_SysEndTime] DEFAULT ('99991231 23:59:59.9999999')
)
GO
ALTER TABLE [Sales].[SalesOrderVehicle] ADD CONSTRAINT [CK_SalesOrderVehicle_IsDeleted_AuditFlag] CHECK (([IsDeleted]='Y' OR [IsDeleted]='N'))
GO
ALTER TABLE [Sales].[SalesOrderVehicle] ADD CONSTRAINT [CK_SalesOrderVehicle_TotalSalePrice_Price] CHECK (([TotalSalePrice]>=(0.00)))
GO
ALTER TABLE [Sales].[SalesOrderVehicle] ADD CONSTRAINT [XPK_SalesOrderVehicle] PRIMARY KEY CLUSTERED ([SalesOrderVehicleID])
GO
ALTER TABLE [Sales].[SalesOrderVehicle] ADD CONSTRAINT [FK_SalesOrderVehicle_Customer] FOREIGN KEY ([CustomerID]) REFERENCES [Sales].[Customer] ([CustomerID])
GO
ALTER TABLE [Sales].[SalesOrderVehicle] ADD CONSTRAINT [FK_SalesOrderVehicle_Staff] FOREIGN KEY ([StaffID]) REFERENCES [HumanResources].[Staff] ([StaffID])
GO
