/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

IF TYPE_ID('[sdSysTime].[DateAdded]') IS NOT NULL
	DROP TYPE [sdSysTime].[DateAdded];

GO
CREATE TYPE [sdSysTime].[DateAdded] FROM datetime2 NULL
GO
