/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

IF TYPE_ID('[dBlob].[sdHashKey]') IS NOT NULL
	DROP TYPE [dBlob].[sdHashKey];

GO
CREATE TYPE [dBlob].[sdHashKey] FROM varbinary (max) NULL
GO
