/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [Sales].[Country]
(
[CountryID] [sdSequenceNumber].[SurrogateKeyNumber] NOT NULL IDENTITY(1, 1),
[CountryName] [sdAddressesString].[CountryString] NULL CONSTRAINT [DF_Country_CountryName_Unavailable] DEFAULT ('Unavailable'),
[CountryISO3] [sdCountryStringVariants].[CountryISO3] NOT NULL CONSTRAINT [DF_Country_CountryISO3_Unavailable] DEFAULT ('Unavailable'),
[CountryISO2] [sdCountryStringVariants].[CountryISO2] NULL CONSTRAINT [DF_Country_CountryISO2_Unavailable] DEFAULT ('Unavailable'),
[SalesRegion] [sdAddressesString].[RegionString] NULL CONSTRAINT [DF_Country_SalesRegion_Unavailable] DEFAULT ('Unavailable'),
[Note] [sdLongTextString].[Note] NOT NULL CONSTRAINT [DF_Country_Note_Note] DEFAULT ('Row was inserted'),
[IsDeleted] [sdFlagString].[AuditFlag] NULL CONSTRAINT [DF_Country_IsDeleted_FlagNo] DEFAULT ('N'),
[TransactionNumber] [sdOrdinalNumber].[TransactionNumber] NULL CONSTRAINT [DF_Country_TransactionNumber_OrdinalNumber] DEFAULT ((1)),
[UserAuthorizationID] [sdSequenceNumber].[SurrogateKeyNumber] NULL,
[SysStartTime] [sdSysTime].[SysStartTime] NULL CONSTRAINT [DF_Country_SysStartTime_Sysdatetime] DEFAULT (sysdatetime()),
[SysEndTime] [sdSysTime].[SysEndTime] NULL CONSTRAINT [DF_Country_SysEndTime_SysEndTime] DEFAULT ('99991231 23:59:59.9999999')
)
GO
ALTER TABLE [Sales].[Country] ADD CONSTRAINT [CK_Country_IsDeleted_AuditFlag] CHECK (([IsDeleted]='Y' OR [IsDeleted]='N'))
GO
ALTER TABLE [Sales].[Country] ADD CONSTRAINT [CK_Country_SalesRegion] CHECK (([SalesRegion]='Asia' OR [SalesRegion]='South America' OR [SalesRegion]='North America' OR [SalesRegion]='EMEA'))
GO
ALTER TABLE [Sales].[Country] ADD CONSTRAINT [CK_Template_CountryISO2_625223618] CHECK (([CountryISO2] like '[A-Z][A-Z]'))
GO
ALTER TABLE [Sales].[Country] ADD CONSTRAINT [CK_Template_CountryISO3_608446401] CHECK (([CountryISO3] like '[A-Z][A-Z][A-Z]'))
GO
ALTER TABLE [Sales].[Country] ADD CONSTRAINT [PK_Country] PRIMARY KEY CLUSTERED ([CountryID])
GO
