/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [Sales].[Customer]
(
[CustomerID] [sdSequenceNumber].[SurrogateKeyNumber] NOT NULL CONSTRAINT [XPK_CustomerID_Sequence] DEFAULT (NEXT VALUE FOR [PKSequence].[CustomerID]),
[CustomerName] [sdPersonNameString].[CustomerName] NULL CONSTRAINT [DF_Customer_CustomerName_Unavailable] DEFAULT ('Unavailable'),
[CustomerAddress1] [sdAddressesString].[AddressString] NULL CONSTRAINT [DF_Customer_CustomerAddress1_Unavailable] DEFAULT ('Unavailable'),
[CustomerAddress2] [sdAddressesString].[AddressString] NULL CONSTRAINT [DF_Customer_CustomerAddress2_Unavailable] DEFAULT ('Unavailable'),
[CustomerTown] [sdAddressesString].[TownString] NULL CONSTRAINT [DF_Customer_CustomerTownUnavailable] DEFAULT ('Unavailable'),
[CustomerPostalCode] [sdAddressesString].[PostalCodeString] NULL CONSTRAINT [DF_Customer_CustomerPostalCode_Unavailable] DEFAULT ('Unavailable'),
[CountryID] [sdSequenceNumber].[SurrogateKeyNumber] NULL CONSTRAINT [DF_Customer_CountryID] DEFAULT ((0)),
[IsCustomerReseller] [sdFlagBit].[FlagFalse] NULL CONSTRAINT [DF_Customer_IsCustomerReseller_FlagFalse] DEFAULT ((0)),
[IsCustomerCreditRisk] [sdFlagBit].[FlagFalse] NULL CONSTRAINT [DF_Customer_IsCustomerCreditRisk_FlagFalse] DEFAULT ((0)),
[CustomerExpenditureClassificationID] [sdSequenceNumber].[SurrogateKeyNumber] NULL,
[Note] [sdLongTextString].[Note] NOT NULL CONSTRAINT [DF_Customer_Note_Note] DEFAULT ('Row was inserted'),
[IsDeleted] [sdFlagString].[AuditFlag] NULL CONSTRAINT [DF_Customer_IsDeleted_FlagNo] DEFAULT ('N'),
[TransactionNumber] [sdOrdinalNumber].[TransactionNumber] NULL CONSTRAINT [DF_Customer_TransactionNumber_OrdinalNumber] DEFAULT ((1)),
[UserAuthorizationID] [sdSequenceNumber].[SurrogateKeyNumber] NULL,
[SysStartTime] [sdSysTime].[SysStartTime] NULL CONSTRAINT [DF_Customer_SysStartTime_Sysdatetime] DEFAULT (sysdatetime()),
[SysEndTime] [sdSysTime].[SysEndTime] NULL CONSTRAINT [DF_Customer_SysEndTime_SysEndTime] DEFAULT ('99991231 23:59:59.9999999')
)
GO
ALTER TABLE [Sales].[Customer] ADD CONSTRAINT [CK_Customer_IsCustomerCreditRisk_FlagBit] CHECK (([IsCustomerCreditRisk]=(1) OR [IsCustomerCreditRisk]=(0)))
GO
ALTER TABLE [Sales].[Customer] ADD CONSTRAINT [CK_Customer_IsCustomerReseller_FlagBit] CHECK (([IsCustomerReseller]=(1) OR [IsCustomerReseller]=(0)))
GO
ALTER TABLE [Sales].[Customer] ADD CONSTRAINT [CK_Customer_IsDeleted_AuditFlag] CHECK (([IsDeleted]='Y' OR [IsDeleted]='N'))
GO
ALTER TABLE [Sales].[Customer] ADD CONSTRAINT [PK_Customer_CustomerID] PRIMARY KEY CLUSTERED ([CustomerID])
GO
ALTER TABLE [Sales].[Customer] ADD CONSTRAINT [FK_Customer_Country] FOREIGN KEY ([CountryID]) REFERENCES [Sales].[Country] ([CountryID]) ON UPDATE CASCADE
GO
ALTER TABLE [Sales].[Customer] ADD CONSTRAINT [FK_Customer_CustomerExpenditureClassification] FOREIGN KEY ([CustomerExpenditureClassificationID]) REFERENCES [Analytics].[CustomerExpenditureClassification] ([CustomerExpenditureClassificationID])
GO
