/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

IF TYPE_ID('[sdVehicleSalePayment].[DiscountedPrice]') IS NOT NULL
	DROP TYPE [sdVehicleSalePayment].[DiscountedPrice];

GO
CREATE TYPE [sdVehicleSalePayment].[DiscountedPrice] FROM numeric (18, 2) NOT NULL
GO
