/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

IF TYPE_ID('[sdPersonNameString].[FirstNameString]') IS NOT NULL
	DROP TYPE [sdPersonNameString].[FirstNameString];

GO
CREATE TYPE [sdPersonNameString].[FirstNameString] FROM nvarchar (25) NOT NULL
GO
