USE [RawEuropeanCarManufacturer]
GO
/****** Object:  Table [RawData].[ManufacturerVehicleModel]    Script Date: 12/2/2022 4:40:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [RawData].[ManufacturerVehicleModel](
	[ManufacturerVehicleModelId] [int] IDENTITY(1,1) NOT NULL,
	[ManufacturerVehicleMakeId] [int] NOT NULL,
	[ManufacturerVehicleModelName] [nvarchar](150) NULL,
	[ManufacturerVehicleModelVariant] [nvarchar](150) NULL,
 CONSTRAINT [PK_Model] PRIMARY KEY CLUSTERED 
(
	[ManufacturerVehicleModelId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [RawData].[ManufacturerVehicleModel] ON 

INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (1, 1, N'Daytona', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (2, 1, N'Testarossa', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (3, 1, N'355', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (4, 1, N'308', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (5, 1, N'Dino', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (6, 1, N'Mondial', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (7, 1, N'F40', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (8, 1, N'F50', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (9, 1, N'360', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (10, 1, N'Enzo', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (11, 2, N'911', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (12, 2, N'924', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (13, 2, N'944', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (14, 2, N'959', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (15, 2, N'928', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (16, 2, N'Boxster', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (17, 3, N'Countach', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (18, 3, N'Diabolo', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (19, 3, N'Jarama', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (20, 3, N'400GT', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (21, 4, N'DB2', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (22, 4, N'DB4', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (23, 4, N'DB5', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (24, 4, N'DB6', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (25, 4, N'DB9', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (26, 4, N'Virage', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (27, 4, N'Vantage', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (28, 4, N'Vanquish', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (29, 4, N'Rapide', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (30, 5, N'Mulsanne', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (31, 5, N'Continental', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (32, 5, N'Flying Spur', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (33, 5, N'Arnage', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (34, 5, N'Brooklands', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (35, 6, N'Phantom', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (36, 6, N'Ghost', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (37, 6, N'Wraith', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (38, 6, N'Silver Shadow', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (39, 6, N'Corniche', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (40, 6, N'Camargue', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (41, 6, N'Silver Seraph', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (42, 7, N'57', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (43, 7, N'62', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (44, 7, N'Exelero', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (45, 8, N'280SL', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (46, 8, N'350SL', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (47, 8, N'500SL', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (48, 8, N'250SL', N'Sports Pagoda')
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (49, 8, N'R107', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (50, 8, N'W107', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (51, 9, N'Giulia', N'Sprint')
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (52, 9, N'Spider', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (53, 9, N'1750', N'GTV')
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (54, 9, N'Giulietta', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (55, 10, N'Lichfield', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (56, 10, N'Princess', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (57, 10, N'Cambridge', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (58, 11, N'Isetta', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (59, 11, N'Alpina', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (60, 11, N'E30', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (61, 12, N'35', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (62, 12, N'Veyron', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (63, 12, N'57C', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (64, 13, N'Torpedo', N'')
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (65, 13, N'Rosalie', N'Coupe')
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (66, 13, N'Traaction Avant', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (67, 14, N'135', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (68, 14, N'145', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (69, 14, N'175', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (70, 15, N'DMC 12', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (71, 16, N'Mark V', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (72, 16, N'Mark X', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (73, 16, N'XJ12', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (74, 16, N'XK120', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (75, 16, N'XK150', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (76, 16, N'XJS', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (77, 16, N'E-Type', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (80, 18, N'P1', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (81, 19, N'Plus 8', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (82, 19, N'Plus 4', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (83, 19, N'Supersport', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (84, 20, N'M14', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (85, 20, N'M600', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (86, 21, N'TR4', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (87, 21, N'TR5', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (88, 21, N'TR6', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (89, 21, N'TR7', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (90, 21, N'GT6', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (91, 21, N'Roadster', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (92, 21, N'Stag', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (93, 21, N'TR3A', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (94, 22, N'500', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (95, 22, N'600', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (96, 23, N'205', N'GTI')
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (97, 23, N'Type VA', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (98, 23, N'404', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (99, 23, N'203', NULL)
INSERT [RawData].[ManufacturerVehicleModel] ([ManufacturerVehicleModelId], [ManufacturerVehicleMakeId], [ManufacturerVehicleModelName], [ManufacturerVehicleModelVariant]) VALUES (100, 24, N'Robin', NULL)
SET IDENTITY_INSERT [RawData].[ManufacturerVehicleModel] OFF
GO
