/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

IF TYPE_ID('[sdSysTime].[SysEndTime]') IS NOT NULL
	DROP TYPE [sdSysTime].[SysEndTime];

GO
CREATE TYPE [sdSysTime].[SysEndTime] FROM datetime2 NOT NULL
GO
