/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

IF TYPE_ID('[dDateTime].[sdSysTime]') IS NOT NULL
	DROP TYPE [dDateTime].[sdSysTime];

GO
CREATE TYPE [dDateTime].[sdSysTime] FROM datetime2 NOT NULL
GO
