/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

IF TYPE_ID('[sdTimeString].[ClassTimeString]') IS NOT NULL
	DROP TYPE [sdTimeString].[ClassTimeString];

GO
CREATE TYPE [sdTimeString].[ClassTimeString] FROM nvarchar (20) NULL
GO
