/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [HumanResources].[Department]
(
[DepartmentName] [sdBusinessComponentString].[DepartmentString] NULL CONSTRAINT [DF_Department_Department_Unavailable] DEFAULT ('Unavailable'),
[DepartmentID] [sdSequenceNumber].[SurrogateKeyNumber] NOT NULL
)
GO
ALTER TABLE [HumanResources].[Department] ADD CONSTRAINT [XPKDepartment] PRIMARY KEY CLUSTERED ([DepartmentID])
GO
