/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

IF TYPE_ID('[sdHashKey].[RowLevelKey]') IS NOT NULL
	DROP TYPE [sdHashKey].[RowLevelKey];

GO
CREATE TYPE [sdHashKey].[RowLevelKey] FROM varbinary (32) NULL
GO
