/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

IF TYPE_ID('[sdFlagString].[AuditFlag]') IS NOT NULL
	DROP TYPE [sdFlagString].[AuditFlag];

GO
CREATE TYPE [sdFlagString].[AuditFlag] FROM nvarchar (20) NULL
GO
