/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

IF TYPE_ID('[dString].[sdLongTextString]') IS NOT NULL
	DROP TYPE [dString].[sdLongTextString];

GO
CREATE TYPE [dString].[sdLongTextString] FROM nvarchar (200) NULL
GO
