/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

IF TYPE_ID('[dString].[sdVehicleString]') IS NOT NULL
	DROP TYPE [dString].[sdVehicleString];

GO
CREATE TYPE [dString].[sdVehicleString] FROM nvarchar (50) NULL
GO
