/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

IF TYPE_ID('[sdAddressesString].[RegionString]') IS NOT NULL
	DROP TYPE [sdAddressesString].[RegionString];

GO
CREATE TYPE [sdAddressesString].[RegionString] FROM nvarchar (20) NULL
GO
